AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to create an Amazon ElastiCache Redis cluster (single node, single AZ).

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC where Redis will be deployed.

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnet for the Redis cluster (single subnet).

  RedisNodeType:
    Type: String
    Default: cache.t3.micro
    Description: ElastiCache Redis node type.
    AllowedValues:
      - cache.t3.micro
      - cache.t3.small
      - cache.t3.medium
      - cache.m6g.large
      - cache.r6g.large

  RedisEngineVersion:
    Type: String
    Default: 7.0
    Description: Redis engine version.

Resources:
  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnet group for Redis
      SubnetIds: !Ref SubnetIds

  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Redis
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          CidrIp: 10.0.0.0/16

  RedisCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      ClusterName: redis-cluster
      Engine: redis
      EngineVersion: !Ref RedisEngineVersion
      CacheNodeType: !Ref RedisNodeType
      NumCacheNodes: 1
      CacheSubnetGroupName: !Ref RedisSubnetGroup
      VpcSecurityGroupIds:
        - !Ref RedisSecurityGroup

Outputs:
  RedisEndpoint:
    Description: Redis primary endpoint
    Value: !GetAtt RedisCluster.RedisEndpoint.Address

  RedisPort:
    Description: Redis port
    Value: !GetAtt RedisCluster.RedisEndpoint.Port
